import { ageLabelOf } from "./utils";
// 导入类型
import type { IVaccineDose } from "./types";

/**
 * 快捷构造剂次模板条目
 * @param key 剂次唯一标识，格式为 "{vaccineKey}-{序号}"，如 "hepb-2"
 * @param vaccineKey 疫苗唯一标识，同一疫苗的多剂次共用，如 "hepb"
 * @param vaccineName 疫苗展示名称，如 "乙肝疫苗"
 * @param dose 当前剂次序号（第几针），从 1 开始
 * @param totalDose 该疫苗全程总剂次数
 * @param recommendAge 推荐接种月龄（数字型，0 表示出生时，48 表示 4 岁）
 * @param plan 疫苗类别："free" 免疫规划（免费）/ "paid" 非免疫规划（自费）
 * @param disease 预防疾病名称
 * @param intro 接种说明补充（可选），如接种间隔、替代关系等
 * @returns 完整的剂次条目 IVaccineDose（ageLabel 由 recommendAge 推导）
 */
function dose(
  key: string,
  vaccineKey: string,
  vaccineName: string,
  dose: number,
  totalDose: number,
  recommendAge: number,
  plan: IVaccineDose["plan"],
  disease: string,
  intro?: string,
): IVaccineDose {
  return {
    key,
    vaccineKey,
    vaccineName,
    dose,
    totalDose,
    recommendAge,
    ageLabel: ageLabelOf(recommendAge),
    plan,
    disease,
    intro,
  };
}

/**
 * 免疫规划疫苗（免费）剂次模板
 * 依据：国家免疫规划疫苗儿童免疫程序表（2021年版），共 11 种 22 剂次
 */
export const FREE_VACCINE_DOSES: IVaccineDose[] = [
  // 卡介苗：出生时 1 剂
  dose("bcg-1", "bcg", "卡介苗", 1, 1, 0, "free", "结核病"),
  // 乙肝疫苗：0、1、6 月龄各 1 剂
  dose(
    "hepb-1",
    "hepb",
    "乙肝疫苗",
    1,
    3,
    0,
    "free",
    "乙型肝炎病毒感染",
    "出生 24 小时内尽早接种第 1 剂",
  ),
  dose("hepb-2", "hepb", "乙肝疫苗", 2, 3, 1, "free", "乙型肝炎病毒感染"),
  dose("hepb-3", "hepb", "乙肝疫苗", 3, 3, 6, "free", "乙型肝炎病毒感染"),
  // 脊灰疫苗：2、3 月龄 IPV，4 月龄、4 岁 bOPV
  dose(
    "polio-1",
    "polio",
    "脊灰疫苗",
    1,
    4,
    2,
    "free",
    "脊髓灰质炎（小儿麻痹症）",
    "第 1、2 剂为 IPV 灭活疫苗",
  ),
  dose(
    "polio-2",
    "polio",
    "脊灰疫苗",
    2,
    4,
    3,
    "free",
    "脊髓灰质炎（小儿麻痹症）",
    "第 1、2 剂为 IPV 灭活疫苗",
  ),
  dose(
    "polio-3",
    "polio",
    "脊灰疫苗",
    3,
    4,
    4,
    "free",
    "脊髓灰质炎（小儿麻痹症）",
    "第 3、4 剂为 bOPV 口服减毒疫苗",
  ),
  dose(
    "polio-4",
    "polio",
    "脊灰疫苗",
    4,
    4,
    48,
    "free",
    "脊髓灰质炎（小儿麻痹症）",
    "第 3、4 剂为 bOPV 口服减毒疫苗",
  ),
  // 百白破疫苗：3、4、5、18 月龄各 1 剂
  dose("dtap-1", "dtap", "百白破疫苗", 1, 4, 3, "free", "百日咳、白喉、破伤风"),
  dose("dtap-2", "dtap", "百白破疫苗", 2, 4, 4, "free", "百日咳、白喉、破伤风"),
  dose("dtap-3", "dtap", "百白破疫苗", 3, 4, 5, "free", "百日咳、白喉、破伤风"),
  dose(
    "dtap-4",
    "dtap",
    "百白破疫苗",
    4,
    4,
    18,
    "free",
    "百日咳、白喉、破伤风",
  ),
  // 白破疫苗：6 岁 1 剂（加强）
  dose(
    "dt-1",
    "dt",
    "白破疫苗",
    1,
    1,
    72,
    "free",
    "白喉、破伤风",
    "6 岁加强免疫",
  ),
  // 麻腮风疫苗：8 月龄、18 月龄各 1 剂
  dose(
    "mmr-1",
    "mmr",
    "麻腮风疫苗",
    1,
    2,
    8,
    "free",
    "麻疹、流行性腮腺炎、风疹",
  ),
  dose(
    "mmr-2",
    "mmr",
    "麻腮风疫苗",
    2,
    2,
    18,
    "free",
    "麻疹、流行性腮腺炎、风疹",
  ),
  // 乙脑减毒活疫苗：8 月龄、2 岁各 1 剂
  dose("je-1", "je", "乙脑减毒活疫苗", 1, 2, 8, "free", "流行性乙型脑炎"),
  dose("je-2", "je", "乙脑减毒活疫苗", 2, 2, 24, "free", "流行性乙型脑炎"),
  // A 群流脑多糖疫苗：6、9 月龄各 2 剂
  dose(
    "mpsv-a-1",
    "mpsv-a",
    "A群流脑多糖疫苗",
    1,
    2,
    6,
    "free",
    "流行性脑脊髓膜炎",
    "两剂间隔 ≥ 3 个月",
  ),
  dose(
    "mpsv-a-2",
    "mpsv-a",
    "A群流脑多糖疫苗",
    2,
    2,
    9,
    "free",
    "流行性脑脊髓膜炎",
    "两剂间隔 ≥ 3 个月",
  ),
  // AC 群流脑多糖疫苗：3 岁、6 岁各 1 剂
  dose(
    "mpsv-ac-1",
    "mpsv-ac",
    "AC群流脑多糖疫苗",
    1,
    2,
    36,
    "free",
    "流行性脑脊髓膜炎",
  ),
  dose(
    "mpsv-ac-2",
    "mpsv-ac",
    "AC群流脑多糖疫苗",
    2,
    2,
    72,
    "free",
    "流行性脑脊髓膜炎",
  ),
  // 甲肝减毒活疫苗：18 月龄 1 剂
  dose("hepa-1", "hepa", "甲肝减毒活疫苗", 1, 1, 18, "free", "甲型肝炎"),
];

/**
 * 非免疫规划疫苗（自费）剂次模板
 * 收录常见自费疫苗 13 种，是否主流见 MAIN_PAID_VACCINE_KEYS
 */
export const PAID_VACCINE_DOSES: IVaccineDose[] = [
  // 五联疫苗：2、3、4 月龄基础 + 18 月龄加强
  dose(
    "dtap-ipv-hib-1",
    "dtap-ipv-hib",
    "五联疫苗",
    1,
    4,
    2,
    "paid",
    "百日咳、白喉、破伤风、脊灰、Hib感染",
    "可替代脊灰+百白破+Hib，减少接种针次",
  ),
  dose(
    "dtap-ipv-hib-2",
    "dtap-ipv-hib",
    "五联疫苗",
    2,
    4,
    3,
    "paid",
    "百日咳、白喉、破伤风、脊灰、Hib感染",
  ),
  dose(
    "dtap-ipv-hib-3",
    "dtap-ipv-hib",
    "五联疫苗",
    3,
    4,
    4,
    "paid",
    "百日咳、白喉、破伤风、脊灰、Hib感染",
  ),
  dose(
    "dtap-ipv-hib-4",
    "dtap-ipv-hib",
    "五联疫苗",
    4,
    4,
    18,
    "paid",
    "百日咳、白喉、破伤风、脊灰、Hib感染",
  ),
  // 13 价肺炎球菌多糖结合疫苗：2、4、6 月龄基础 + 12~15 月龄加强
  dose(
    "pcv13-1",
    "pcv13",
    "13价肺炎疫苗",
    1,
    4,
    2,
    "paid",
    "肺炎球菌引起的肺炎、脑膜炎等",
    "最早 6 周龄可接种，各剂间隔 ≥ 28 天",
  ),
  dose(
    "pcv13-2",
    "pcv13",
    "13价肺炎疫苗",
    2,
    4,
    4,
    "paid",
    "肺炎球菌引起的肺炎、脑膜炎等",
  ),
  dose(
    "pcv13-3",
    "pcv13",
    "13价肺炎疫苗",
    3,
    4,
    6,
    "paid",
    "肺炎球菌引起的肺炎、脑膜炎等",
  ),
  dose(
    "pcv13-4",
    "pcv13",
    "13价肺炎疫苗",
    4,
    4,
    12,
    "paid",
    "肺炎球菌引起的肺炎、脑膜炎等",
    "12~15 月龄加强",
  ),
  // 口服五价轮状病毒疫苗：6~12 周龄起服，3 剂间隔 4~10 周
  dose(
    "rotavirus-1",
    "rotavirus",
    "口服轮状疫苗",
    1,
    3,
    2,
    "paid",
    "轮状病毒肠胃炎",
    "五价疫苗，6~12 周龄起服，每剂间隔 4~10 周",
  ),
  dose(
    "rotavirus-2",
    "rotavirus",
    "口服轮状疫苗",
    2,
    3,
    3,
    "paid",
    "轮状病毒肠胃炎",
  ),
  dose(
    "rotavirus-3",
    "rotavirus",
    "口服轮状疫苗",
    3,
    3,
    4,
    "paid",
    "轮状病毒肠胃炎",
  ),
  // EV71 手足口疫苗：6 月龄起 2 剂，间隔 1 个月
  dose(
    "ev71-1",
    "ev71",
    "手足口疫苗",
    1,
    2,
    6,
    "paid",
    "EV71感染引起的手足口病",
    "两剂间隔 1 个月，适用 6 月龄~5 岁",
  ),
  dose(
    "ev71-2",
    "ev71",
    "手足口疫苗",
    2,
    2,
    7,
    "paid",
    "EV71感染引起的手足口病",
  ),
  // 水痘减毒活疫苗：12 月龄、4 岁各 1 剂
  dose(
    "varicella-1",
    "varicella",
    "水痘疫苗",
    1,
    2,
    12,
    "paid",
    "水痘",
    "推荐 12 月龄和 4 岁各接种 1 剂",
  ),
  dose(
    "varicella-2",
    "varicella",
    "水痘疫苗",
    2,
    2,
    48,
    "paid",
    "水痘",
    "推荐 12 月龄和 4 岁各接种 1 剂",
  ),
  // 流感疫苗：6 月龄起每年接种
  dose(
    "influenza-1",
    "influenza",
    "流感疫苗",
    1,
    1,
    6,
    "paid",
    "流行性感冒",
    "6 月龄以上每年接种；首次接种需 2 剂间隔 ≥ 4 周",
  ),
  // b 型流感嗜血杆菌疫苗：3、4、5 月龄基础 + 18 月龄加强
  dose(
    "hib-1",
    "hib",
    "Hib疫苗",
    1,
    4,
    3,
    "paid",
    "Hib引起的脑膜炎、肺炎等",
    "b型流感嗜血杆菌疫苗",
  ),
  dose("hib-2", "hib", "Hib疫苗", 2, 4, 4, "paid", "Hib引起的脑膜炎、肺炎等"),
  dose("hib-3", "hib", "Hib疫苗", 3, 4, 5, "paid", "Hib引起的脑膜炎、肺炎等"),
  dose("hib-4", "hib", "Hib疫苗", 4, 4, 18, "paid", "Hib引起的脑膜炎、肺炎等"),
  // 甲肝灭活疫苗：18、24 月龄各 1 剂（自费替代）
  dose(
    "hepa-i-1",
    "hepa-i",
    "甲肝灭活疫苗",
    1,
    2,
    18,
    "paid",
    "甲型肝炎",
    "免疫规划甲肝减毒活疫苗的自费替代",
  ),
  dose("hepa-i-2", "hepa-i", "甲肝灭活疫苗", 2, 2, 24, "paid", "甲型肝炎"),
  // 乙脑灭活疫苗：8 月龄 2 剂（间隔 7~10 天）+ 2 岁、6 岁各 1 剂
  dose(
    "je-i-1",
    "je-i",
    "乙脑灭活疫苗",
    1,
    4,
    8,
    "paid",
    "流行性乙型脑炎",
    "8 月龄 2 剂间隔 7~10 天，2 岁、6 岁各 1 剂",
  ),
  dose("je-i-2", "je-i", "乙脑灭活疫苗", 2, 4, 9, "paid", "流行性乙型脑炎"),
  dose("je-i-3", "je-i", "乙脑灭活疫苗", 3, 4, 24, "paid", "流行性乙型脑炎"),
  dose("je-i-4", "je-i", "乙脑灭活疫苗", 4, 4, 72, "paid", "流行性乙型脑炎"),
  // 23 价肺炎球菌多糖疫苗：2 岁以上高危人群 1 剂
  dose(
    "ppsv23-1",
    "ppsv23",
    "23价肺炎疫苗",
    1,
    1,
    24,
    "paid",
    "肺炎球菌感染",
    "适用于 2 岁以上感染高危人群",
  ),
  // AC 群流脑结合疫苗：6 月龄起 2 剂（替代 A 群流脑）
  dose(
    "menac-1",
    "menac",
    "AC流脑结合疫苗",
    1,
    2,
    6,
    "paid",
    "A群、C群流脑感染",
    "可替代 A 群流脑多糖疫苗",
  ),
  dose(
    "menac-2",
    "menac",
    "AC流脑结合疫苗",
    2,
    2,
    7,
    "paid",
    "A群、C群流脑感染",
    "可替代 A 群流脑多糖疫苗",
  ),
  // 四价流脑多糖疫苗：3 岁、6 岁（替代 AC 流脑多糖）
  dose(
    "mpsv4-1",
    "mpsv4",
    "四价流脑疫苗",
    1,
    2,
    36,
    "paid",
    "A、C、Y、W135群流脑感染",
    "替代 AC 流脑多糖疫苗",
  ),
  dose(
    "mpsv4-2",
    "mpsv4",
    "四价流脑疫苗",
    2,
    2,
    72,
    "paid",
    "A、C、Y、W135群流脑感染",
    "替代 AC 流脑多糖疫苗",
  ),
  // 霍乱疫苗：口服 3 剂（0、7、28 天）
  dose(
    "cholera-1",
    "cholera",
    "霍乱疫苗",
    1,
    1,
    24,
    "paid",
    "霍乱",
    "口服 3 剂，分别于 0、7、28 天服用",
  ),
];
